-- FinSiS ERP Database Schema
-- Run this script on the DBS.FDB Firebird database

-- Table: SUPPLIERS (Fornecedores)
CREATE TABLE SUPPLIERS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(18),
    EMAIL VARCHAR(254) NOT NULL,
    PHONE VARCHAR(12)
);

CREATE GENERATOR GEN_SUPPLIERS_ID;
SET GENERATOR GEN_SUPPLIERS_ID TO 0;

CREATE TRIGGER SUPPLIERS_BI FOR SUPPLIERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SUPPLIERS_ID, 1);
END;

-- Table: USUARIOS (Users)
CREATE TABLE USUARIOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(254) NOT NULL
);

CREATE GENERATOR GEN_USUARIOS_ID;
SET GENERATOR GEN_USUARIOS_ID TO 0;

CREATE TRIGGER USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_USUARIOS_ID, 1);
END;

-- Table: CONTAS_A_PAGAR (Accounts Payable)
CREATE TABLE CONTAS_A_PAGAR (
    ID INTEGER NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    VALUE DECIMAL(10,2) NOT NULL,
    DUE_DATE DATE NOT NULL,
    SUPPLIER VARCHAR(255),
    STATUS VARCHAR(20) DEFAULT 'PENDENTE'
);

CREATE GENERATOR GEN_CONTAS_A_PAGAR_ID;
SET GENERATOR GEN_CONTAS_A_PAGAR_ID TO 0;

CREATE TRIGGER CONTAS_A_PAGAR_BI FOR CONTAS_A_PAGAR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CONTAS_A_PAGAR_ID, 1);
END;

-- Table: CONTAS_A_RECEBER (Accounts Receivable)
CREATE TABLE CONTAS_A_RECEBER (
    ID INTEGER NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    VALUE DECIMAL(10,2) NOT NULL,
    DUE_DATE DATE NOT NULL,
    CUSTOMER VARCHAR(255),
    STATUS VARCHAR(20) DEFAULT 'PENDENTE'
);

CREATE GENERATOR GEN_CONTAS_A_RECEBER_ID;
SET GENERATOR GEN_CONTAS_A_RECEBER_ID TO 0;

CREATE TRIGGER CONTAS_A_RECEBER_BI FOR CONTAS_A_RECEBER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CONTAS_A_RECEBER_ID, 1);
END;

-- Insert sample data
INSERT INTO SUPPLIERS (NAME, CNPJ, EMAIL, PHONE) VALUES ('Fornecedor Exemplo', '12.345.678/0001-90', 'contato@fornecedor.com', '11987654321');
INSERT INTO USUARIOS (NAME, USERNAME, PASSWORD, EMAIL) VALUES ('Administrador', 'admin', '123456', 'admin@finsis.com');
INSERT INTO CONTAS_A_PAGAR (DESCRIPTION, VALUE, DUE_DATE, SUPPLIER, STATUS) VALUES ('Pagamento de aluguel', 1500.00, '2025-12-01', 'Imobiliaria ABC', 'PENDENTE');
INSERT INTO CONTAS_A_RECEBER (DESCRIPTION, VALUE, DUE_DATE, CUSTOMER, STATUS) VALUES ('Venda produto X', 2500.00, '2025-12-15', 'Cliente João Silva', 'PENDENTE');

COMMIT;
